### ISSUE TITLE
minSeverity

### ISSUE THREAD

**Issue by aaronstutzer** [prymitive/pint-action#45]
when I add `minSeverity` to my github action I get a warning:
`Unexpected input(s) 'minSeverity', valid inputs are ['entryPoint', 'args', 'token', 'workdir', 'config', 'loglevel']`

my config:
```
      - name: Run pint
        uses: prymitive/pint-action@v1
        with:
          workdir: 'rules'
          minSeverity: 'fatal'
```

how can I change the `minSeverity` ?
